# Generated by Django 2.2.1 on 2019-08-12 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 14, 28, 34, 178185)),
        ),
    ]
