# Generated by Django 2.2.1 on 2019-08-12 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_requests_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 17, 7, 35, 131114)),
        ),
    ]
