# Generated by Django 2.2.1 on 2019-08-14 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20190812_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 5, 0, 43, 688233)),
        ),
    ]
